# This is a basic workflow to help you get started with Actions

name: JAVA CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:          

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Set up Java 1.8
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with: 
        java-version: 1.8

    # Runs the rest template project
    - name: Build with Maven rest template project
      run: mvn -B package --file customer-java-resttemplate/pom.xml
      
    # Runs the webflux java project
    - name: Build with Maven webflux java project
      run: mvn -B package --file  customer-java-webflux/pom.xml   
      
    # Runs the webflux kotkin project
    - name: Build with Maven webflux kotlin project
      run: mvn -B package --file customer-kotlin-webflux/pom.xml
      
    # Runs the coroutines project
    - name: Build with Maven coroutines project
      run: mvn -B package --file customer-kotlin-coroutines/pom.xml
